### ISSUE TITLE
Thank you message

### ISSUE THREAD

**Issue by Zeioth** [AvinashReddy3108/Gogh4Termux#1]
You are doing god's work. Thank you for making it so easy to use.
Have a merry christmas!!

**Comment by Zeioth** [comment]
If you have something similar to set NerdFonts, it would be awesome.

**Comment by AvinashReddy3108** [comment]
Of course I have one for that (it lags a bit due to the huge amount of fonts tho)

https://gist.github.com/5d7719fa742ab959a07394abac729ab2

PS: it's part of my LITMux project: https://github.com/AvinashReddy3108/LitMux/blob/master/install.sh#L159

**Comment by AvinashReddy3108** [comment]
Closing this issue as off-topic.

**Comment by AvinashReddy3108** [comment]
Thanks, and I wish you a happy new year!
