### ISSUE TITLE
Selenized theme missing

### ISSUE THREAD

**Issue by stablestud** [AvinashReddy3108/Gogh4Termux#3]
Hi, just found your repo in a Goph comment.

I would like to run termux with the Selenized theme which is available "upstream" (Goph) but its missing here.
Could please you regenerate the Termux themes against the newest Goph release?

Thank you very much :)

**Comment by AvinashReddy3108** [comment]
> Hi, just found your repo in a Goph comment.

Finally! :partying_face: 

> I would like to run termux with the Selenized theme which is available "upstream" (Goph) but its missing here. Could please you regenerate the Termux themes against the newest Goph release?

Done :)

> Thank you very much :)

Much appreciated!

**Comment by stablestud** [comment]
Thank you! :)
